### ISSUE TITLE
在ios手机上加某些动画，背景图片会闪烁一下

### ISSUE THREAD

**Issue by licong96** [littledu/pageSlide#12]
我给页面的某些元素加了animate.css里面的一些动画，在ios11手机上切换动画，背景图片会消失出现白色背景然后又出现图片，类似于背景图片显示隐藏了一下，我以为是图片丢失了，所以给当前page页面加了红色背景，发现背景图消失的那一刹出现的还是白色背景。

只有给页面的元素使用一些特殊的动画才会出现，比如 flipInX、zommIn这些动画，而有些动画却没有问题。

[这是测试地址](https://licong96.github.io/test/year/pageSlider.html)

**Comment by littledu** [comment]
@licong96 
![image](https://user-images.githubusercontent.com/1784673/35952994-8a516d26-0cbd-11e8-86c3-f26df0e8807d.png)
看了下，flipInX 等都是3d动画，我试了去掉 page  的 `perspective` 属性就不会闪了。你可以试下

**Comment by licong96** [comment]
@littledu 确实有用，非常感谢
