### ISSUE TITLE
请问能够禁止上下滚动吗

### ISSUE THREAD

**Issue by arieslee** [littledu/pageSlide#17]
请问能够禁止上下滚动吗?
我只需要左右滚动，定义了direction: 'vertical'
但是我的页面长些，垂直滑动的时候也会触发onSwipeLeft和onSwipeRight

**Comment by littledu** [comment]
![image](https://user-images.githubusercontent.com/1784673/126991959-160f0ac0-4438-43da-ac72-5233cf0202fa.png)
参考这里
